repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: detect-private-key
      - id: check-json
  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.12.5
    hooks:
    - id: ruff-check
    - id: ruff-format
