# Generated by Django 5.2.4 on 2025-07-31 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0003_alter_household_uuid_and_more"),
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IngredientCategory",
            new_name="IngredientsCategory",
        ),
    ]
