# Generated by Django 5.2.4 on 2025-08-01 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0003_alter_household_uuid_and_more"),
        ("ingredients", "0002_rename_ingredientcategory_ingredientscategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientscategory",
            name="description",
            field=models.TextField(
                blank=True, max_length=300, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="ingredientscategory",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="households.household",
                verbose_name="Household",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientscategory",
            name="is_system",
            field=models.BooleanField(default=False, verbose_name="System Value"),
        ),
        migrations.AlterField(
            model_name="ingredientscategory",
            name="name",
            field=models.CharField(max_length=40, verbose_name="Name"),
        ),
    ]
