# Generated by Django 5.2.4 on 2025-08-01 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0003_alter_ingredientscategory_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredientscategory",
            options={"verbose_name_plural": "Ingredient Categories"},
        ),
    ]
