# Generated by Django 5.2.4 on 2025-08-01 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0004_alter_householdmember_options"),
        ("ingredients", "0004_alter_ingredientscategory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40, verbose_name="Name")),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="System Value"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingredients.ingredientscategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="households.household",
                        verbose_name="Household",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "household", "category")},
            },
        ),
    ]
