# Generated by Django 5.2.4 on 2025-08-01 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0003_alter_household_uuid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="householdmember",
            options={
                "verbose_name": "Household Memnber",
                "verbose_name_plural": "Household Members",
            },
        ),
    ]
